name: Build & Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build C
        run: |
          cd app
          make all
      - name: Run All Testcases
        run: |
          python tools/run_testcases.py ALL
