name: Tag & Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag (e.g., SCR_000001_implemented or Release_1.0)"
        required: true
      tag_message:
        description: "Message"
        required: true
jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a "${{ inputs.tag_name }}" -m "${{ inputs.tag_message }}"
          git push origin "${{ inputs.tag_name }}"
